const APP_CONSTANTS = require('./application');
const CONFIG_COMMAND_CONSTANTS = require('./configCommands');
const COMMAND_CONSTANTS = require('./commands');
const MESSAGE_CONSTANTS = require('./messages');
const REGEX_CONSTANTS = require('./regex');
const COLLECTION_CONSTANTS = require('./collections');

module.exports.APP_CONSTANTS = APP_CONSTANTS;
module.exports.CONFIG_COMMAND_CONSTANTS = CONFIG_COMMAND_CONSTANTS;
module.exports.COMMAND_CONSTANTS = COMMAND_CONSTANTS;
module.exports.MESSAGE_CONSTANTS = MESSAGE_CONSTANTS;
module.exports.REGEX_CONSTANTS = REGEX_CONSTANTS;
module.exports.COLLECTION_CONSTANTS = COLLECTION_CONSTANTS;

module.exports = {
  APP_CONSTANTS,
  CONFIG_COMMAND_CONSTANTS,
  COMMAND_CONSTANTS,
  MESSAGE_CONSTANTS,
  REGEX_CONSTANTS,
  COLLECTION_CONSTANTS,
};
